# Generated by Django 4.2.4 on 2023-09-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('teams', '0003_alter_userfollowteammodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('file', models.FileField(blank=True, null=True, upload_to=posts.models.post_file_path, validators=[posts.models.validate_file_extension], verbose_name='رسانه')),
                ('numbers_of_seen', models.IntegerField(default=0, verbose_name='تعداد مشاهدات')),
                ('is_news', models.BooleanField(verbose_name='خبر')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ ها')),
                ('teams', models.ManyToManyField(to='teams.teammodel', verbose_name='تیم ها')),
            ],
            options={
                'verbose_name': 'پست',
            },
        ),
        migrations.CreateModel(
            name='PostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_reply', models.BooleanField(default=False, verbose_name='ریپلای است؟')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.postmodel', verbose_name='پست')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.postcommentmodel', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
            },
        ),
    ]
