# Generated by Django 4.2.4 on 2023-09-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_userfollowteammodel_options'),
        ('posts', '0004_alter_postmodel_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='teams',
            field=models.ManyToManyField(blank=True, to='teams.teammodel', verbose_name='تیم ها'),
        ),
    ]
