# Generated by Django 4.2.4 on 2023-08-06 07:18

from django.db import migrations, models
import statuses.models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusmodel',
            options={'ordering': ['-created'], 'verbose_name': 'استاتوس'},
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=statuses.models.status_file_path, validators=[statuses.models.validate_file_extension], verbose_name='رسانه'),
        ),
    ]
