# Generated by Django 4.2.4 on 2023-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_statusmodel_options_alter_statusmodel_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='statusmodel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('to_user', models.F('from_user')), _negated=True), ('is_private', False), _connector='OR'), name='only messages can be private'),
        ),
    ]
