# Generated by Django 4.2.4 on 2023-08-06 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0003_statusmodel_only_messages_can_be_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscommentmodel',
            options={'ordering': ['-created'], 'verbose_name': 'لایک کردن استاتوس'},
        ),
        migrations.AlterModelOptions(
            name='statuslikemodel',
            options={'verbose_name': 'کامنت برای استاتوس'},
        ),
        migrations.AlterUniqueTogether(
            name='statuslikemodel',
            unique_together={('user', 'status')},
        ),
    ]
