# Generated by Django 4.2.4 on 2023-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_alter_statuscommentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscommentmodel',
            options={'ordering': ['created'], 'verbose_name': 'کامنت برای استاتوس'},
        ),
        migrations.AlterModelOptions(
            name='statusmodel',
            options={'ordering': ['-is_pin', '-created'], 'verbose_name': 'استاتوس'},
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='statusmodel',
            constraint=models.CheckConstraint(check=models.Q(('to_user', models.F('from_user')), ('is_pin', False), _connector='OR'), name='only statuses can be pin'),
        ),
    ]
