# Generated by Django 4.2.4 on 2023-08-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blockmodel_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcodemodel',
            options={'verbose_name': 'کد یکبار مصرف'},
        ),
    ]
