# Generated by Django 4.2.4 on 2023-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcodemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_phone_verified',
            field=models.BooleanField(default=True),
        ),
    ]
