# Generated by Django 4.2.4 on 2023-09-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmodel',
            name='reason',
            field=models.CharField(blank=True, choices=[('A', 'گزارش این شناسه کاربری'), ('B', 'گزارش مطالب و دیدگاه\u200cهای این کاربر'), ('C', 'هیچی، فقط با این کاربر حال نمی\u200cکنم'), ('D', 'دلایل دیگری وجود دارد')], max_length=1, null=True),
        ),
    ]
